export const initialOrder = {
  firstName: '',
  lastName: '',
  phone: '',
  email: '',
  country: '',
  city: '',
  street: '',
  apartment: '',
  postCode: '',
  cardNumber: '',
  cardHolder: '',
  expiryDate: '',
  cvcCode: '',
};
